name: kita_hack_2026
description: "A Flutter app for tracking parcels within universities."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  qr_flutter: ^4.1.0 
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  mobile_scanner: ^5.1.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
